version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
  producer:
    build: .
    command: node src/producer.js
    environment:
      - MIN=1
      - MAX=10
      - PRODUCER_COUNT=2
    depends_on:
      - redis
    networks:
      - app-network
  consumer:
    build: .
    command: node src/consumer.js
    environment:
      - MIN=1
      - MAX=10
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
